services:
  - type: cron
    name: scraper-vivienda
    schedule: "0 0 */15 * *"    # Cada 15 días a las 00:00 UTC
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"
